---
- name: Get user accounts | DTAG SEC Req 3.21-4
  command: "awk -F: '{print $1}' /etc/passwd"
  changed_when: False
  always_run: True
  register: users

- name: delete rhosts-files from system | DTAG SEC Req 3.21-4
  file: dest='~{{ item }}/.rhosts' state=absent
  with_items: '{{ users.stdout_lines }}'
  when: ansible_distribution != 'Container Linux by CoreOS'

- name: delete hosts.equiv from system | DTAG SEC Req 3.21-4
  file: dest='/etc/hosts.equiv' state=absent
  when: ansible_distribution != 'Container Linux by CoreOS'
